"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 3.2.9.
For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import logging
import os
from distutils.util import strtobool
from pathlib import Path
from typing import overload

import django
import django.utils.encoding
import ecs_logging
import sentry_sdk

# patch https://stackoverflow.com/questions/70382084/import-error-force-text-from-django-utils-encoding
from corsheaders.defaults import default_headers
from django.core.cache import DEFAULT_CACHE_ALIAS
from django.db import DEFAULT_DB_ALIAS
from django.utils.encoding import force_str
from dotenv import load_dotenv
from import_export.formats.base_formats import CSV, JSON, TSV, XLSX


def env_bool(name: str, default: bool = False) -> bool:
    val = env_str(name, str(default)) or str(default)
    return strtobool(val) == 1


@overload
def env_str(name: str, default: str) -> str: ...

@overload  # noqa: E302
def env_str(name: str, default: None = None) -> str | None: ...


def env_str(name: str, default: str | None = None) -> str | None:
    return os.getenv(name, default)


logger = logging.getLogger(__name__)

VERSION = '0.0.40'
logger.warning(f'Settings Version - Start: {VERSION}')

django.utils.encoding.force_text = force_str  # type: ignore[attr-defined]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DOTENV_FILE = env_str('DOTENV', os.path.join(BASE_DIR, 'config/local.env'))

if os.path.exists(DOTENV_FILE):
    logger.warning(f'Loading environment from DOTENV={DOTENV_FILE}')
    load_dotenv(DOTENV_FILE)
else:
    logger.warning(f'DOTENV - No environment file found at DOTENV={DOTENV_FILE}')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!

DEBUG = env_bool('DJANGO_DEBUG', False)
DEFAULT_USER_TEST = env_str('DJANGO_DEFAULT_USER_TEST', 'admin')  # only for local login the user if there is no user logged in

# The default user to execute automatic system operations. i.e. scheduled tasks, automatic signatures...
# The default set of permissions available for the system user(s). For instance, the permission to sign documents.
FRONTEND_URL = env_str('FRONTEND_URL', 'http://localhost:3000')
API_SYSTEM_USER = env_str('API_SYSTEM_USER', 'system')
API_SYSTEM_PERMISSION_GROUP = env_str('API_SYSTEM_PERMISSION_GROUP', 'boilerworks_automatic_system_operations')

# Django
SECRET_KEY = env_str('DJANGO_SECRET_KEY', 'not-a-secret')
ROOT_URLCONF = env_str('DJANGO_ROOT_URLCONF', 'config.urls')
BASE_URL = env_str('DJANGO_BASE_URL', 'app/')
LOGIN_REDIRECT_URL = env_str('DJANGO_LOGIN_REDIRECT_URL', f'/{BASE_URL}admin/')
SWITCHED_FROM_USER = 'switched_from_user'

CORS_ALLOW_CREDENTIALS = env_bool('DJANGO_CORS_ALLOW_CREDENTIALS', True)
CORS_ALLOW_ALL_ORIGINS = env_bool('DJANGO_CORS_ALLOW_ALL_ORIGINS', True)
CORS_ALLOW_HEADERS = default_headers + ('sentry-trace', 'baggage', 'x-platform',)
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_DATABASE_CACHE_BACKEND = 'default'

CORS_ORIGIN_WHITELIST = (
    'https://storage.googleapis.com',
)

WSGI_APPLICATION = 'config.wsgi.application'

LANGUAGE_CODE = env_str('DJANGO_LANGUAGE_CODE', 'en')
TIME_ZONE = env_str('DJANGO_TIME_ZONE', 'UTC')
SYSTEM_TIME_ZONE = env_str('SYSTEM_TIME_ZONE', 'UTC')
USE_I18N = env_bool('DJANGO_USE_I18N', True)
USE_L10N = env_bool('DJANGO_USE_L10N', True)
USE_TZ = env_bool('DJANGO_USE_TZ', True)

LANGUAGES = [
    ('en', "English"),
    ('es', "Spanish"),
]

CONFIGURATION = env_str('DJANGO_CONFIGURATION', )

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = env_str('DJANGO_STATIC_URL', '/static/')

# Google
GOOGLE_API_KEY = env_str('DJANGO_GOOGLE_API_KEY')
# DEFAULT_FILE_STORAGE = env_str('DJANGO_', )
GS_BUCKET_NAME = env_str('DJANGO_GS_BUCKET_NAME')
GS_DIR = env_str('DJANGO_GS_DIR')

GOOGLE_APPLICATION_CREDENTIALS = env_str('GOOGLE_APPLICATION_CREDENTIALS')
GOOGLE_MAPS_API_KEY = env_str('GOOGLE_MAPS_API_KEY')

ROCKETCHAT_URL = env_str('ROCKETCHAT_URL', '')
ROCKETCHAT_API_USER_ID = env_str('ROCKETCHAT_API_USER_ID', '')
ROCKETCHAT_API_AUTH_TOKEN = env_str('ROCKETCHAT_API_AUTH_TOKEN', '')

# Load Auth0 application settings into memory
AUTH0_DOMAIN = os.environ.get("AUTH0_DOMAIN")
AUTH0_CLIENT_ID = os.environ.get("AUTH0_CLIENT_ID")
AUTH0_CLIENT_SECRET = os.environ.get("AUTH0_CLIENT_SECRET")
AUTH0_CLIENT_SCOPES = os.environ.get("AUTH0_CLIENT_SCOPES", "openid profile email read:users create:users update:users")
AUTH0_DATABASE_CONNECTION_ID = os.environ.get("AUTH0_DATABASE_CONNECTION_ID", "Username-Password-Authentication")
CLIENT_SESSION_API_KEY = os.environ.get("CLIENT_SESSION_API_KEY")

# EMail Configuration
AWS_SES_REGION_NAME = os.environ.get('AWS_SES_REGION_NAME', 'us-west-2')
AWS_SES_REGION_ENDPOINT = os.environ.get('AWS_SES_REGION_ENDPOINT', 'email.us-west-2.amazonaws.com')
EMAIL_BACKEND = env_str('DJANGO_EMAIL_BACKEND', "django_ses.SESBackend")
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 25))
FROM_EMAIL = os.environ.get("FROM_EMAIL", "no-reply@example.com")


# Firebase configuration
def var2file(variable):
    if (content := os.environ.get(variable)) is None:
        return None
    if os.path.exists(content):
        return content
    filename = f'/tmp/{variable}'
    with open(filename, 'w') as stream:
        stream.write(content)
    return filename


# firebase credentials
FIREBASE_ADMIN_SDK = var2file("FIREBASE_ADMIN_SDK")

# Start of AWS Buckets
USE_S3 = env_bool('USE_S3', True)

if USE_S3:
    # aws / s3-compatible settings (works with AWS S3, MinIO, etc.)
    SERVER_NAME = env_str('SERVER_NAME', 'localhost')
    AWS_ACCESS_KEY_ID = env_str('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env_str('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env_str('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = env_str('AWS_S3_ENDPOINT_URL', '')  # MinIO: http://minio-local:9000
    AWS_S3_CUSTOM_DOMAIN = env_str('AWS_S3_CUSTOM_DOMAIN', '')
    if not AWS_S3_CUSTOM_DOMAIN:
        if AWS_S3_ENDPOINT_URL:
            AWS_S3_CUSTOM_DOMAIN = None  # Let boto3 use endpoint URL directly
        else:
            AWS_S3_CUSTOM_DOMAIN = f'static.{SERVER_NAME.replace("local", "dev")}'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = True  # Required for pre-signed URLs with MinIO

    # s3 static settings
    AWS_LOCATION = ''
    STATIC_URL = '/static/'
    STORAGES = {
        "default": {
            "BACKEND": 'storages.backends.s3boto3.S3Boto3Storage',
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
else:
    STATIC_URL = '/staticfiles/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

MEDIA_URL = '/mediafiles/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')

# MEDIA_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# End of AWS Buckets

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    DEFAULT_DB_ALIAS: {
        'ENGINE': env_str('POSTGRES_ENGINE'),
        'NAME': env_str('POSTGRES_DB'),
        'USER': env_str('POSTGRES_USER'),
        'PASSWORD': env_str('POSTGRES_PASSWORD'),
        'HOST': env_str('POSTGRES_HOST'),
        'PORT': env_str('POSTGRES_PORT'),
        'OPTIONS': {
            'options': '-c search_path=public'
        },
    },
}

DATABASE_ROUTERS = []

CACHES = {
    DEFAULT_CACHE_ALIAS: {
        # 'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("DJANGO_CACHE_URL"),
    },
    'memory_cache': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# OpenSearch
OPENSEARCH_URL = os.environ.get('OPENSEARCH_URL', 'http://localhost:9200')

CSRF_TRUSTED_ORIGINS = [
    'https://storage.googleapis.com/',
    'http://localhost:3000',
    'http://localhost:80',
    'https://localhost:443',
    'https://localhost:8443',
]

# Application definition
INSTALLED_APPS = [
    # Start of Django Standard
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'strawberry_django',
    'phonenumber_field',
    'core',
    'rolepermissions',
    'django_filters',
    'djmoney',
    'nested_admin',
    "sslserver",
    'storages',
    'django_crontab',
    'import_export',
    'simple_history',
    'forms',
    'workflows',
    'copilot',
    'core_rule_engine',
    # End of Django Standard

    # Start of Celery
    'django_celery_results',
    'django_celery_beat',
    # End of Celery

    # Start of Email
    'django_ses',
    # End of Email

    # Start of health_check
    'health_check',  # required
    'health_check.db',  # stock Django health checkers
    'health_check.cache',
    'health_check.storage',
    'health_check.contrib.migrations',
    'health_check.contrib.celery_ping',  # pings a celery worker
    # 'health_check.contrib.celery',  # dispatches a task and waits for it
    # 'health_check.contrib.psutil',  # disk and memory utilization; requires psutil
    # 'health_check.contrib.s3boto3_storage',  # requires boto3 and S3BotoStorage backend
    # 'health_check.contrib.rabbitmq',  # requires RabbitMQ broker
    # 'health_check.contrib.redis',  # requires Redis broker
    # End of health_check

    # Start of Push notifications
    # "push_notifications", # It does not work here, it is
    "pushnotif",
    # End of Push notifications

    # Start of Boilerworks
    'auth1',
    'config.middleware',
    'organization',
    'core_ui',
    'core_logs',
    'triage',
    # End of Boilerworks

    'constance',
    'constance.backends.database',
]

# Feature toggles — remove disabled feature apps
from config.features import filter_installed_apps  # noqa: E402

INSTALLED_APPS = filter_installed_apps(INSTALLED_APPS)

# Discover and merge domain app configurations
# Domain apps declare their configuration
# in boilerworks_config/settings.py files
logger.info('Discovering domain apps...')
from config.config_merger import ConfigMerger  # noqa: E402

config_merger = ConfigMerger(BASE_DIR)
config_merger.discover()

# Merge INSTALLED_APPS from domain apps
DOMAIN_APPS = config_merger.get_installed_apps()
INSTALLED_APPS.extend(DOMAIN_APPS)
logger.info(f'Added {len(DOMAIN_APPS)} domain app(s) to INSTALLED_APPS')

# Merge MIDDLEWARE from domain apps
DOMAIN_MIDDLEWARE = config_merger.get_middleware()
if DOMAIN_MIDDLEWARE:
    # MIDDLEWARE will be extended after it's defined below
    pass

# Merge custom settings from domain apps
config_merger.merge_settings(globals())

CRONJOBS = [

]

CONSTANCE_CONFIG = dict(
    TIME_ZONE=(TIME_ZONE, 'System Timezone to apply forms and other time related operations'),
    ENABLE_FREQUENCY_CHECK=(True, 'Enable frequency check for forms submissions'),
    NEW_FORM_SUBM_ACCESS_CONTROL=(False, 'Enables the new access control flow for forms submissions'),
    PUT_PRESIGNED_URL_EXPIRATION=(60, 'Time to live in seconds of presigned urls for uploading.'),
    GET_PRESIGNED_URL_EXPIRATION=(3600, 'Time to live in seconds of presigned urls for downloading.'),
    AUTH0_REGISTER_NEW_USER=(False, 'Register new users in Auth0'),
    SEARCH_PROFILE_ENABLED=(False, 'Enables opensearch for profile search'),
    EMAIL_NOTIFICATIONS=(False, 'Enables the platform to send Email Notifications'),
    SMS_NOTIFICATIONS=(False, 'Enables the platform to sent SMS Notifications'),
    WEBAPP_NOTIFICATIONS=(False, 'Enables the platform to send Web Application Notifications'),
    PUSH_NOTIFICATIONS=(False, 'Enables the platform to send Push Notifications'),
)

CONSTANCE_CONFIG_FIELDSETS = {
    'System': {
        'fields': ('TIME_ZONE', 'PUT_PRESIGNED_URL_EXPIRATION', 'GET_PRESIGNED_URL_EXPIRATION'),
        'collapse': False
    },
    'Forms': {
        'fields': ('ENABLE_FREQUENCY_CHECK',),
        'collapse': False
    },
    'FormSubmissions': {
        'fields': ('NEW_FORM_SUBM_ACCESS_CONTROL',),
        'collapse': False
    },
    'Auth0': {
        'fields': ('AUTH0_REGISTER_NEW_USER',),
        'collapse': False
    },
    'Search': {
        'fields': ('SEARCH_PROFILE_ENABLED',),
        'collapse': False
    },
    'Notifications': {
        'fields': ('EMAIL_NOTIFICATIONS', 'SMS_NOTIFICATIONS', 'WEBAPP_NOTIFICATIONS', 'PUSH_NOTIFICATIONS',),
        'collapse': False
    },
}

INTERNAL_IPS = [
    "127.0.0.1",
]

DEBUG_TOOLBAR_CONFIG = {
    # Show toolbar whenever DEBUG=True, regardless of request IP (needed for Docker)
    "SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG,
    # Allow test runs without removing debug_toolbar from INSTALLED_APPS
    "IS_RUNNING_TESTS": False,
}

# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    'django_ratelimit.middleware.RatelimitMiddleware',
    # Determines Ip ranges supported, specific hosts are managed via the ALLOWED_HOSTS setting in each env
    'config.middleware.allow_cidr_hosts.AllowCIDRHostsMiddleware',
    "django.middleware.common.CommonMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'auth1.middleware.Auth0SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware',  # Required for Auth0
    'core.middleware.current_user.CurrentUserMiddleware',  # Track current user for signals
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.middleware.gzip.GZipMiddleware',

]

TEMPLATES_CACHE_BACKEND = DEFAULT_CACHE_ALIAS

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'config/templates/')],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    [
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                        "core.loaders.template.Loader",
                    ],
                ),
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # 'config.backend.MagicBackend',
]

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DATE_INPUT_FORMATS": [
        "%Y-%m-%d",           # 1962-08-15
        "%Y-%m-%dT%H:%M:%S",  # 1962-08-15T00:00:00
        "iso-8601",           # keep DRF's default
    ],
    "DATETIME_INPUT_FORMATS": [
        "%Y-%m-%dT%H:%M:%S",  # 1962-08-15T00:00:00
        "iso-8601",
    ],
}

# Rate limiting
RATELIMIT_VIEW = 'django.views.defaults.permission_denied'

# CELERY Start
CELERY_APP_NAME = env_str('CELERY_APP_NAME', 'boilerworks')
CELERY_BACKEND = os.getenv('CELERY_BACKEND')
CELERY_BROKER = os.getenv('CELERY_BROKER')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = DEFAULT_CACHE_ALIAS
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACK_LATE = True
CELERY_TASK_TIME_LIMIT = 60 * 60  # seconds
CELERY_TIMEZONE = "MST"
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_RESULT_EXTENDED = True
CELERY_TASK_ALWAYS_EAGER = False

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10


#  We need to verify how to apply priority to queues
#  CELERY_BROKER_TRANSPORT_OPTIONS = {
#      'priority_steps': list(range(10)),
#      'sep': ':',
#      'queue_order_strategy': 'priority',
#  }

CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,  # 1 hour
    'fanout_prefix': True,
    'fanout_patterns': True,
    'ssl_cert_reqs': None,  # Disable SSL certificate verification for rediss://
}

# CELERY End


class CoreStdlibFormatter(ecs_logging.StdlibFormatter):
    def format_to_ecs(self, record):
        result = super().format_to_ecs(record)

        # Inject OTel trace context as proper ECS nested fields:
        #   {"trace": {"id": "<32-char hex>"}, "span": {"id": "<16-char hex>"}}
        from opentelemetry import trace
        span = trace.get_current_span()
        if span.is_recording():
            ctx = span.get_span_context()
            if ctx.is_valid:
                result["trace"] = {"id": format(ctx.trace_id, "032x")}
                result["span"] = {"id": format(ctx.span_id, "016x")}

        return result


TELEMETRY_LOGS = env_bool('TELEMETRY_LOGS', True)
# ECS JSON logging for all non-local environments.
# Local/LocalPG/LocalVerbose override this below with plain text.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        "ecs_formatter": {
            "()": CoreStdlibFormatter,
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'ecs_formatter',
        },
        'ecs': {
            'class': 'logging.StreamHandler',
            'formatter': 'ecs_formatter',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['ecs'],
            'level': env_str('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# ================ DEV
CONFIGURATION = env_str('DJANGO_CONFIGURATION', "Dev")
logger.warning(f'DJANGO_CONFIGURATION: {CONFIGURATION}')

SENTRY_DSN = env_str('SENTRY_DSN')

match CONFIGURATION.lower():
    case 'stg' | 'dev' | 'prd' | 'prod':
        if SENTRY_DSN:
            sentry_sdk.init(
                dsn=SENTRY_DSN,
                traces_sample_rate=1.0,
                profiles_sample_rate=1.0,
                environment=CONFIGURATION,
            )
        else:
            logger.info('Sentry DSN not configured; skipping Sentry init')
    case _:
        logger.info(f'Sentry is not enabled for configuration: {CONFIGURATION}')

ALLOWED_HOSTS = ['*', ]

IS_PROD = CONFIGURATION.lower() == "prd"
IS_DEV = CONFIGURATION.lower() == "dev" or CONFIGURATION.lower() == "local"
IS_LOCAL = CONFIGURATION.lower() in ("local", "localpg", "localverbose")

if CONFIGURATION.lower() == "Prd".lower():
    DEBUG = True
    AUTH_PASSWORD_VALIDATORS = []
    ALLOWED_HOSTS = [
        '127.0.0.1',
        'localhost',
        '*'
    ]
elif CONFIGURATION.lower() == "Dev".lower():
    DEBUG = True
    AUTH_PASSWORD_VALIDATORS = []
    ALLOWED_HOSTS = [
        '127.0.0.1',
        'localhost',
        '*'
    ]

elif CONFIGURATION.lower() == "int":
    DEBUG = True
    AUTH_PASSWORD_VALIDATORS = []
    ALLOWED_HOSTS = [
        '127.0.0.1',
        'localhost',
        '*'
    ]

elif CONFIGURATION.lower() == "stg":
    DEBUG = True
    AUTH_PASSWORD_VALIDATORS = []
    ALLOWED_HOSTS = [
        '127.0.0.1',
        'localhost',
        '*'
    ]
elif CONFIGURATION.lower() == "Tests".lower():
    DEBUG = True
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_BROKER = "memory://"
    CELERY_BACKEND = "memory://"
    SECRET_KEY = 'not-a-secret'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:'
        }
    }
    CACHES = {
        DEFAULT_CACHE_ALIAS: {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        },
        'memory_cache': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
    INSTALLED_APPS.append('testdata')
elif CONFIGURATION.lower() == "Local".lower() or CONFIGURATION.lower() == "LocalPG".lower():
    DEBUG = True
    ALLOWED_HOSTS = ['*', ]
    AUTH_PASSWORD_VALIDATORS = []
    DEFAULT_USER_TEST = env_str('DJANGO_', 'admin')  # only for local login the user if there is no user logged in
    TELEMETRY_LOGS = False
    INSTALLED_APPS.append('testdata')
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': env_str('DJANGO_LOG_LEVEL', 'INFO'),
                'propagate': False,
            },
        },
    }
elif CONFIGURATION.lower() == "LocalVerbose".lower():
    DEBUG = True
    ALLOWED_HOSTS = ['*', ]
    AUTH_PASSWORD_VALIDATORS = []
    DEFAULT_USER_TEST = env_str('DJANGO_', 'admin')  # only for local login the user if there is no user logged in
    TELEMETRY_LOGS = False

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': env_str('DJANGO_LOG_LEVEL', 'INFO'),
                'propagate': False,
            },
        },
    }
else:
    DEBUG = True
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_BROKER = "memory://"
    CELERY_BACKEND = "memory://"
    SECRET_KEY = 'not-a-secret'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:'
        }
    }
    CACHES = {
        DEFAULT_CACHE_ALIAS: {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        },
        'memory_cache': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }

logger.warning(f'Settings Version - End: {VERSION}')
logger.warning(f'DATABASE: {DATABASES[DEFAULT_DB_ALIAS]["ENGINE"]}')
logger.warning(f'DB NAME: {DATABASES[DEFAULT_DB_ALIAS]["NAME"]}')
if "USER" in DATABASES[DEFAULT_DB_ALIAS]:
    logger.warning(f'DB USER: {DATABASES[DEFAULT_DB_ALIAS]["USER"]}')
logger.warning(f'ALLOWED_HOSTS: {ALLOWED_HOSTS}')


# multiple import options
IMPORT_FORMATS = [JSON]

# single export options
EXPORT_FORMATS = [JSON, TSV, CSV, XLSX]

# Twilio Settings
TWILIO_SID = os.getenv('TWILIO_SID', '')
TWILIO_SECRET = os.getenv('TWILIO_SECRET', '')
TWILIO_FROM_NUMBER = os.getenv('TWILIO_FROM_NUMBER', '')
TWILIO_CALLBACK = os.getenv('TWILIO_CALLBACK', '')

# Start of Metabase Config
METABASE_SITE_URL = env_str('METABASE_SITE_URL', '')
METABASE_SECRET_KEY = env_str('METABASE_SECRET_KEY', '')
METABASE_BACKEND_API_KEY = env_str('METABASE_BACKEND_API_KEY', '')

logger.warning(f"METABASE_URL = {METABASE_SITE_URL}")

# Copilot (Pydantic AI + AG-UI) — feature-flagged via FEATURE_COPILOT.
# ANTHROPIC_API_KEY is read lazily when a request is served, so an unset key
# only disables the copilot at request time (it never breaks startup/tests).
ANTHROPIC_API_KEY = env_str('ANTHROPIC_API_KEY')
COPILOT_MODEL = env_str('COPILOT_MODEL', 'anthropic:claude-haiku-4-5')
# Skill delivery (CopilotKit Intelligence Automatic Learning): before each run the agent pulls the published
# Skills of the configured Learning Container from the Next.js runtime, which holds the Intelligence key.
# Server-to-server only (docker network); empty disables it. See copilot/learned_skills.py.
COPILOT_SKILLS_URL = env_str('COPILOT_SKILLS_URL', 'http://ui:3000/api/copilotkit-skills')
COPILOT_SKILLS_CACHE_SECONDS = int(env_str('COPILOT_SKILLS_CACHE_SECONDS', '60'))
logger.warning(f"METABASE_SECRET_KEY = {METABASE_SECRET_KEY}")
