# Generated by Django 5.2.12 on 2026-03-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GQLLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "operation_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("platform", models.TextField(blank=True, max_length=100, null=True)),
                ("variables", models.JSONField(blank=True, null=True)),
                ("query", models.TextField(blank=True, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("response", models.JSONField(blank=True, editable=False, null=True)),
                ("error", models.TextField(blank=True, editable=False, null=True)),
                (
                    "duration_millis",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "verbose_name": "GQL Log",
                "verbose_name_plural": "GQL Logs",
            },
        ),
        migrations.CreateModel(
            name="PermissionAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("granted", "Granted"),
                            ("denied", "Denied"),
                            ("used_in_filter", "Used in filter"),
                            ("detail", "Detail of the result"),
                        ],
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("raised_error", models.BooleanField(default=False, editable=False)),
                (
                    "description",
                    models.TextField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "verbose_name": "Permission Access Log",
                "verbose_name_plural": "Permission Access Logs",
            },
        ),
    ]
