# Generated by Django 5.2.12 on 2026-03-17 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("given_name", models.CharField(max_length=1024)),
                ("family_name", models.CharField(max_length=1024)),
                ("nickname", models.CharField(max_length=1024)),
                ("name", models.CharField(max_length=1024)),
                ("picture", models.CharField(max_length=1024)),
                ("locale", models.CharField(max_length=1024)),
                ("updated_at", models.DateTimeField()),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("email_verified", models.BooleanField()),
                ("iss", models.URLField()),
                ("aud", models.CharField(max_length=128)),
                ("iat", models.IntegerField()),
                ("exp", models.IntegerField()),
                (
                    "sub",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("sid", models.CharField(max_length=128)),
                ("nonce", models.CharField(max_length=128)),
                (
                    "internal_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Authentication",
            fields=[
                ("access_token", models.CharField(max_length=8192)),
                (
                    "id_token",
                    models.CharField(
                        max_length=8192, primary_key=True, serialize=False
                    ),
                ),
                ("scope", models.CharField(max_length=8192, null=True)),
                ("iat", models.IntegerField(null=True)),
                ("token_type", models.CharField(max_length=32, null=True)),
                ("expires_at", models.IntegerField(null=True)),
                ("expires_in", models.IntegerField(default=0, null=True)),
                (
                    "userinfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userinfos",
                        to="auth1.userinfo",
                    ),
                ),
            ],
        ),
    ]
