#!/bin/bash
set -e
echo POSTGRES_USER=$POSTGRES_USER
echo POSTGRES_DB=$POSTGRES_DB
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE $POSTGRES_USER;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_USER TO $POSTGRES_USER;
EOSQL
