# Generated by Django 6.0.7 on 2026-07-12 13:04

import uuid

import core.models.common
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="The item slug that will be used",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="If the item is enabled it will be executed",
                    ),
                ),
                ("registered", models.BooleanField(default=False, editable=False)),
                (
                    "description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                (
                    "post_transaction",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="If the action should be executed after the transaction is committed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Definitions/Action",
                "verbose_name_plural": "Definitions/Actions",
            },
        ),
        migrations.CreateModel(
            name="ConditionDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="The item slug that will be used",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="If the item is enabled it will be executed",
                    ),
                ),
                ("registered", models.BooleanField(default=False, editable=False)),
                (
                    "description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Definitions/Condition",
                "verbose_name_plural": "Definitions/Conditions",
            },
        ),
        migrations.CreateModel(
            name="Payload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuleProviderDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(editable=False, max_length=100)),
                ("slug", models.SlugField(editable=False, max_length=100, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": " Providers/Rule Provider",
                "verbose_name_plural": "Providers/Rules",
            },
        ),
        migrations.CreateModel(
            name="ActionPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_positions",
                        to="core_rule_engine.actiondefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConditionPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_positions",
                        to="core_rule_engine.conditiondefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalRuleDefinition",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("slug", models.SlugField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "operant",
                    models.CharField(
                        choices=[("AND", "AND"), ("OR", "OR")],
                        default="AND",
                        help_text="The operant that will be used to combine the conditions in the rule",
                        max_length=5,
                    ),
                ),
                (
                    "run_on_task",
                    models.BooleanField(
                        default=True,
                        help_text="If the rule should be executed on celery",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="If the rule is disabled it will not be executed",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Definitions/Rule",
                "verbose_name_plural": "historical Definitions/Rules",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRuleModelSignal",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "when",
                    models.CharField(
                        choices=[
                            ("custom", "Custom"),
                            ("pre_init", "Pre Init"),
                            ("post_init", "Post Init"),
                            ("pre_save", "Pre Save"),
                            ("post_save", "Post Save"),
                            ("pre_delete", "Pre Delete"),
                            ("post_delete", "Post Delete"),
                            ("m2m_changed", "M2M Changed"),
                            ("pre_migrate", "Pre Migrate"),
                            ("post_migrate", "Post Migrate"),
                        ],
                        db_index=True,
                        help_text="The signals that will trigger the rule",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                (
                    "last_executed",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_registered",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The content type that triggered the rule",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Triggers/Model Signal",
                "verbose_name_plural": "historical Triggers/Model Signals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RuleDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "operant",
                    models.CharField(
                        choices=[("AND", "AND"), ("OR", "OR")],
                        default="AND",
                        help_text="The operant that will be used to combine the conditions in the rule",
                        max_length=5,
                    ),
                ),
                (
                    "run_on_task",
                    models.BooleanField(
                        default=True,
                        help_text="If the rule should be executed on celery",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="If the rule is disabled it will not be executed",
                    ),
                ),
                (
                    "actions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The actions that will be executed when the rule is triggered.Run in a transaction.",
                        related_name="rules_definitions",
                        through="core_rule_engine.ActionPosition",
                        to="core_rule_engine.actiondefinition",
                    ),
                ),
                (
                    "conditions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The conditions that must be met for the rule to be executed all conditions must be met for the rule to be executed",
                        related_name="rules_definitions",
                        through="core_rule_engine.ConditionPosition",
                        to="core_rule_engine.conditiondefinition",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payload",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rules_definitions",
                        to="core_rule_engine.payload",
                    ),
                ),
                (
                    "post_transaction_actions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Actions that will be executed after the transaction is committed",
                        related_name="post_transaction_rules_definitions",
                        to="core_rule_engine.actiondefinition",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Definitions/Rule",
                "verbose_name_plural": "Definitions/Rules",
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.AddField(
            model_name="conditionposition",
            name="rule_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="condition_positions",
                to="core_rule_engine.ruledefinition",
            ),
        ),
        migrations.AddField(
            model_name="actionposition",
            name="rule_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_positions",
                to="core_rule_engine.ruledefinition",
            ),
        ),
        migrations.CreateModel(
            name="RuleExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_id",
                    models.BigIntegerField(
                        editable=False,
                        help_text="The id of the instance that triggered the rule",
                    ),
                ),
                ("success", models.BooleanField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="The content type of the instance that triggered the rule",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_executions",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_executions",
                        to="core_rule_engine.ruledefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Executions/Rule ",
                "verbose_name_plural": "Executions/Rules",
            },
        ),
        migrations.CreateModel(
            name="ConditionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField(editable=False)),
                ("debug", models.JSONField(blank=True, editable=False, null=True)),
                (
                    "exception",
                    models.TextField(
                        blank=True, editable=False, max_length=1000, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "condition",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="condition_executions",
                        to="core_rule_engine.conditiondefinition",
                    ),
                ),
                (
                    "rule_execution",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_rule_engine.ruleexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Executions/Condition ",
                "verbose_name_plural": "Executions/Conditions",
            },
        ),
        migrations.CreateModel(
            name="ActionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField(editable=False)),
                ("debug", models.JSONField(blank=True, editable=False, null=True)),
                (
                    "exception",
                    models.TextField(
                        blank=True, editable=False, max_length=1000, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="action_executions",
                        to="core_rule_engine.actiondefinition",
                    ),
                ),
                (
                    "rule_execution",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_rule_engine.ruleexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Executions/Action ",
                "verbose_name_plural": "Executions/Actions",
            },
        ),
        migrations.AddField(
            model_name="conditiondefinition",
            name="rule_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core_rule_engine.ruleproviderdefinition",
            ),
        ),
        migrations.AddField(
            model_name="actiondefinition",
            name="rule_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core_rule_engine.ruleproviderdefinition",
            ),
        ),
        migrations.CreateModel(
            name="RuleModelSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "when",
                    models.CharField(
                        choices=[
                            ("custom", "Custom"),
                            ("pre_init", "Pre Init"),
                            ("post_init", "Post Init"),
                            ("pre_save", "Pre Save"),
                            ("post_save", "Post Save"),
                            ("pre_delete", "Pre Delete"),
                            ("post_delete", "Post Delete"),
                            ("m2m_changed", "M2M Changed"),
                            ("pre_migrate", "Pre Migrate"),
                            ("post_migrate", "Post Migrate"),
                        ],
                        help_text="The signals that will trigger the rule",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                (
                    "last_executed",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_registered",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The content type that triggered the rule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_signals",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rules",
                    models.ManyToManyField(
                        help_text="The rules that will be triggered by the signal",
                        related_name="signals",
                        to="core_rule_engine.ruledefinition",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Triggers/Model Signal",
                "verbose_name_plural": "Triggers/Model Signals",
                "unique_together": {("when", "content_type")},
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
    ]
