# Generated by Django 6.0.3 on 2026-03-24 17:48

import core.models.common
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_add_profile_timezone'),
        ('organization', '0002_historicalorganization_historicalorganizationmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('form_type', models.CharField(choices=[('standard', 'Standard'), ('multi_step', 'Multi-Step Wizard'), ('modal', 'Modal / Dialog'), ('survey', 'Survey'), ('assessment', 'Quiz / Assessment'), ('data_entry', 'Data Entry'), ('partial', 'Partial / Embeddable Fragment')], default='standard', help_text='Controls rendering behavior (multi-step, modal, survey, etc.)', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('schema', models.JSONField(default=dict, help_text='JSON Schema defining the form fields, types, and validation rules')),
                ('field_config', models.JSONField(blank=True, default=dict, help_text='Per-field configuration beyond JSON Schema. Keys are field names, values are objects with: weight (numeric, for scoring), question_type (rating/scale/matrix/ranking/etc.), step (int, for multi-step forms), order (int, display sequence), randomize (bool, shuffle options for surveys), logic (conditional visibility rules), placeholder, help_text, x-widget override.')),
                ('logic_rules', models.JSONField(blank=True, default=list, help_text='Form-level logic rules. Each rule: {"condition": {"field": "X", "op": "eq|neq|gt|lt|in|contains", "value": ...}, "action": "show|hide|skip_to|require|set_value", "target": "field_or_step_name"}')),
                ('scoring', models.JSONField(blank=True, default=dict, help_text='Scoring configuration for assessments/quizzes. {"total_points": N, "passing_score": N, "show_results": bool}')),
                ('prefill', models.JSONField(blank=True, default=dict, help_text='Prefill configuration. Maps field names to data sources: {"field_name": {"source": "user_profile|url_param|previous_submission|static", "key": "..."}}')),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_forms', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict, help_text='Submitted data, validated against the form schema at submit time')),
                ('secure_payload', models.BinaryField(blank=True, help_text='Encrypted fields (fields marked secure in field_config are stored here, not in payload)', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (partial save)'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(help_text='The exact form version this submission was created against', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms.formdefinition')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='organization.organization')),
                ('signed_by', models.ForeignKey(blank=True, help_text='PIN transaction used to sign this submission (if form requires signature)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='core.pintransaction')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFormDefinition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('form_type', models.CharField(choices=[('standard', 'Standard'), ('multi_step', 'Multi-Step Wizard'), ('modal', 'Modal / Dialog'), ('survey', 'Survey'), ('assessment', 'Quiz / Assessment'), ('data_entry', 'Data Entry'), ('partial', 'Partial / Embeddable Fragment')], default='standard', help_text='Controls rendering behavior (multi-step, modal, survey, etc.)', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('schema', models.JSONField(default=dict, help_text='JSON Schema defining the form fields, types, and validation rules')),
                ('field_config', models.JSONField(blank=True, default=dict, help_text='Per-field configuration beyond JSON Schema. Keys are field names, values are objects with: weight (numeric, for scoring), question_type (rating/scale/matrix/ranking/etc.), step (int, for multi-step forms), order (int, display sequence), randomize (bool, shuffle options for surveys), logic (conditional visibility rules), placeholder, help_text, x-widget override.')),
                ('logic_rules', models.JSONField(blank=True, default=list, help_text='Form-level logic rules. Each rule: {"condition": {"field": "X", "op": "eq|neq|gt|lt|in|contains", "value": ...}, "action": "show|hide|skip_to|require|set_value", "target": "field_or_step_name"}')),
                ('scoring', models.JSONField(blank=True, default=dict, help_text='Scoring configuration for assessments/quizzes. {"total_points": N, "passing_score": N, "show_results": bool}')),
                ('prefill', models.JSONField(blank=True, default=dict, help_text='Prefill configuration. Maps field names to data sources: {"field_name": {"source": "user_profile|url_param|previous_submission|static", "key": "..."}}')),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical form definition',
                'verbose_name_plural': 'historical form definitions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFormSubmission',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict, help_text='Submitted data, validated against the form schema at submit time')),
                ('secure_payload', models.BinaryField(blank=True, help_text='Encrypted fields (fields marked secure in field_config are stored here, not in payload)', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (partial save)'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(blank=True, db_constraint=False, help_text='The exact form version this submission was created against', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forms.formdefinition')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.organization')),
                ('signed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='PIN transaction used to sign this submission (if form requires signature)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.pintransaction')),
                ('submitted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical form submission',
                'verbose_name_plural': 'historical form submissions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='formdefinition',
            constraint=models.UniqueConstraint(fields=('slug', 'version'), name='unique_form_slug_version'),
        ),
    ]
