# Generated by Django 6.0.3 on 2026-03-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdefinition',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='historicalformdefinition',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
