# Generated by Django 6.0.3 on 2026-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_override_slug_non_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow anonymous/unauthenticated submissions'),
        ),
        migrations.AddField(
            model_name='historicalformdefinition',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow anonymous/unauthenticated submissions'),
        ),
    ]
