# Generated by Django 6.0.3 on 2026-03-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_add_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='notification_config',
            field=models.JSONField(blank=True, default=dict, help_text='Notification settings. {"on_submit": {"notify": ["form_owner"|"submitter"|user_id], "subject_template": "...", "message_template": "..."}, "on_status_change": {"notify": [...], "subject_template": "...", "message_template": "..."}}'),
        ),
        migrations.AddField(
            model_name='historicalformdefinition',
            name='notification_config',
            field=models.JSONField(blank=True, default=dict, help_text='Notification settings. {"on_submit": {"notify": ["form_owner"|"submitter"|user_id], "subject_template": "...", "message_template": "..."}, "on_status_change": {"notify": [...], "subject_template": "...", "message_template": "..."}}'),
        ),
    ]
