# Generated by Django 6.0.3 on 2026-03-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_profile_timezone'),
        ('forms', '0004_add_notification_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='attachments',
            field=models.ManyToManyField(blank=True, help_text='File uploads attached to this submission (for file field types)', related_name='form_submissions', to='core.upload'),
        ),
    ]
