# Generated by Django 5.2.12 on 2026-03-17 20:55

import uuid

import core.fields.hash_field
import core.models.authorization.principal
import core.models.common
import core.models.library.directory
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django.db.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth1", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("app_label", models.CharField(max_length=128)),
                ("classname", models.CharField(max_length=1024)),
                ("member", models.CharField(max_length=128)),
                ("parameters", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="GlobalIDLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                (
                    "gid",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        validators=[core.models.common.validate_gid],
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=256)),
                (
                    "type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Interval",
            fields=[
                (
                    "name",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("ordinal", models.IntegerField(db_index=True, default=0)),
                (
                    "hashcode",
                    core.fields.hash_field.HashField(
                        db_index=True, default=0, editable=False
                    ),
                ),
                ("duration", models.CharField(max_length=64)),
                ("unit", models.CharField(max_length=64)),
                ("pay_period", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("ordinal",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PermissionSharedResourcePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_option",
                    models.IntegerField(
                        choices=[(0, "Published"), (1, "Drafted"), (2, "Rejected")],
                        default=0,
                    ),
                ),
                (
                    "is_us_citizen",
                    models.BooleanField(
                        help_text="True if the user is a US citizen, false otherwise.",
                        null=True,
                    ),
                ),
                (
                    "rocket_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("name_suffix", models.CharField(blank=True, max_length=50, null=True)),
                ("nickname", models.CharField(blank=True, max_length=100, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FEMALE", "Female"),
                            ("MALE", "Male"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "emergency_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SMS", "SMS"),
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("es", "Spanish")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("pin", models.CharField(blank=True, max_length=128, null=True)),
                ("pin_salt", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "search",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Search field for user profile",
                        null=True,
                    ),
                ),
                ("show_weekends", models.BooleanField(default=True)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        null=True,
                        verbose_name="username",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_email", "Can view email field"),
                    ("change_email", "Can change email field"),
                    ("view_first_name", "Can view first_name field"),
                    ("change_first_name", "Can change first_name field"),
                    ("view_last_name", "Can view last_name field"),
                    ("change_last_name", "Can change last_name field"),
                    ("view_is_us_citizen", "Can view is_us_citizen field"),
                    ("change_is_us_citizen", "Can change is_us_citizen field"),
                    ("view_avatar", "Can view avatar field"),
                    ("change_avatar", "Can change avatar field"),
                    ("view_signature", "Can view signature field"),
                    ("change_signature", "Can change signature field"),
                    ("view_middle_name", "Can view middle_name field"),
                    ("change_middle_name", "Can change middle_name field"),
                    ("view_display_name", "Can view display_name field"),
                    ("change_display_name", "Can change display_name field"),
                    ("view_name_suffix", "Can view name_suffix field"),
                    ("change_name_suffix", "Can change name_suffix field"),
                    ("view_nickname", "Can view nickname field"),
                    ("change_nickname", "Can change nickname field"),
                    ("view_birth_date", "Can view birth_date field"),
                    ("change_birth_date", "Can change birth_date field"),
                    ("view_gender", "Can view gender field"),
                    ("change_gender", "Can change gender field"),
                    ("view_address", "Can view address field"),
                    ("change_address", "Can change address field"),
                    ("view_phone_number", "Can view phone_number field"),
                    ("change_phone_number", "Can change phone_number field"),
                    (
                        "view_emergency_phone_number",
                        "Can view emergency_phone_number field",
                    ),
                    (
                        "change_emergency_phone_number",
                        "Can change emergency_phone_number field",
                    ),
                    (
                        "view_emergency_contact_name",
                        "Can view emergency_contact_name field",
                    ),
                    (
                        "change_emergency_contact_name",
                        "Can change emergency_contact_name field",
                    ),
                    (
                        "view_emergency_contact_relationship",
                        "Can view emergency_contact_relationship field",
                    ),
                    (
                        "change_emergency_contact_relationship",
                        "Can change emergency_contact_relationship field",
                    ),
                    ("view_preferred_contact", "Can view preferred_contact field"),
                    ("change_preferred_contact", "Can change preferred_contact field"),
                    (
                        "change_reset_password_users",
                        "Can reset password of other users",
                    ),
                    ("delete_users", "Can delete users"),
                    ("approve_profile_changes", "Can approve profile changes"),
                ),
            },
            bases=(
                core.models.common.RequiresApproveMixin,
                core.models.common.ModelPermissionsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ResourceFile",
            fields=[
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gid",
                    models.UUIDField(
                        help_text="Unique resource file id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="User friendly name", max_length=250),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("file", models.FileField(blank=True, null=True, upload_to=None)),
            ],
            options={
                "abstract": False,
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SharedDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=128)),
                ("display_name", models.CharField(max_length=128)),
                ("path", models.CharField(max_length=1024, unique=True)),
                ("hidden", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("path",),
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
            managers=[
                ("objects", core.models.library.directory.SharedDirectoryManager()),
            ],
        ),
        migrations.CreateModel(
            name="SharedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("path", models.CharField(max_length=1024, unique=True)),
            ],
            options={
                "ordering": ("path",),
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
            managers=[
                ("objects", core.models.library.directory.SharedFileManager()),
            ],
        ),
        migrations.CreateModel(
            name="SharedResourceName",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=1024, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "global_id",
                    models.CharField(max_length=1024, null=True, unique=True),
                ),
            ],
            managers=[
                (
                    "objects",
                    core.models.authorization.principal.SharedResourceNameManager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SharedResourcePermission",
            fields=[
                ("ordinal", models.IntegerField(db_index=True, default=0)),
                (
                    "hashcode",
                    core.fields.hash_field.HashField(
                        db_index=True, default=0, editable=False
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ("ordinal",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SharedResourcePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=1024)),
            ],
            options={
                "abstract": False,
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SignRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("sign_required", "Sign Required"),
                            ("canceled", "Canceled"),
                            ("signed", "Signed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "signs_required",
                    models.IntegerField(
                        default=1,
                        help_text="Number of signs required.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date when the all the signatures were completed.",
                        null=True,
                    ),
                ),
                (
                    "cancel_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date when the request was rejected.",
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Note to add details.", null=True
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("change_cancel", "Can cancel the request"),
                    ("change_sign", "Can sign the request"),
                    ("view_all", "Can view the requests of all users"),
                ),
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SiteLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("key", models.CharField(db_index=True, max_length=150)),
                ("text", models.TextField(blank=True, default="")),
            ],
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SourceSharedResourcePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TargetSharedResourcePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        verbose_name="name",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="content")),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                (
                    "last_changed",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="last changed"
                    ),
                ),
            ],
            options={
                "verbose_name": "template",
                "verbose_name_plural": "templates",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the file.",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the file.", null=True
                    ),
                ),
                ("public_url", models.CharField(max_length=4096, unique=True)),
                ("pre_signed_url", models.CharField(max_length=4096)),
                (
                    "path",
                    models.CharField(
                        blank=True, max_length=512, null=True, unique=True
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="Content type of the file. Also known as MIME type.",
                        max_length=256,
                    ),
                ),
                (
                    "target_global_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Entity the upload belongs to (i.e. a review, a course, an employee...)",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "location",
                    models.CharField(
                        choices=[("STATIC", "static"), ("PUBLIC", "public")],
                        default="static",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="UserSwitchGroup",
            fields=[
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Principal",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth1.userinfo",),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address_line_one", models.CharField(blank=True, max_length=250)),
                ("address_line_two", models.CharField(blank=True, max_length=250)),
                ("city", models.CharField(blank=True, max_length=256)),
                ("state", django.db.models.CharField(blank=True, max_length=100)),
                ("street", models.CharField(blank=True, max_length=500)),
                (
                    "zipcode",
                    django.db.models.CharField(blank=True, max_length=20),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_address_line_one", "Can view address_line_one field"),
                    ("change_address_line_one", "Can change address_line_one field"),
                    ("view_address_line_two", "Can view address_line_two field"),
                    ("change_address_line_two", "Can change address_line_two field"),
                    ("view_city", "Can view city field"),
                    ("change_city", "Can change city field"),
                    ("view_state", "Can view state field"),
                    ("change_state", "Can change state field"),
                    ("view_street", "Can view street field"),
                    ("change_street", "Can change street field"),
                    ("view_zipcode", "Can view zipcode field"),
                    ("change_zipcode", "Can change zipcode field"),
                ),
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(blank=True, max_length=256)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ApprovalPropertyWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute", models.CharField(max_length=50)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_whitelists",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataProcess",
            fields=[
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("file_name", models.CharField(blank=True, max_length=130, null=True)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("CSV", "text/csv"),
                            ("TSV", "text/tab-separated-values"),
                            ("JSON", "application/json"),
                            ("API", "api/endpoint"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("FIELDFLO", "FieldFlo"),
                            ("SITE_LABEL", "Site label"),
                            ("PERMISSIONS", "Permissions"),
                            ("COMPONENTS", "Components"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("IGNORED", "Ignored"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "status_date",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Date when the status was updated",
                        null=True,
                    ),
                ),
                (
                    "status_description",
                    models.CharField(
                        blank=True, editable=False, max_length=1024, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Data Processes",
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DataProcessEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Row data", null=True
                    ),
                ),
                (
                    "line_number",
                    models.IntegerField(help_text="Line number in uploaded file."),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("IGNORED", "Ignored"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "status_date",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Date when the status was updated",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="core.dataprocess",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Data Processes Entities",
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GlobalIDMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obj_guid",
                    models.CharField(
                        db_index=True, editable=False, max_length=100, unique=True
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_id_maps",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MetabaseChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("DASHBOARD", "dashboard"), ("QUESTION", "question")],
                        default="dashboard",
                        max_length=32,
                    ),
                ),
                ("metabase_chart_id", models.IntegerField()),
                ("title", models.CharField(max_length=250)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Metabase Chart",
                "verbose_name_plural": "Metabase Charts",
                "ordering": ["-created_at"],
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MetabaseUnimportedChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metabase_chart_id", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("DASHBOARD", "dashboard"), ("QUESTION", "question")],
                        default="dashboard",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("creator_email", models.CharField(max_length=100)),
                ("is_embedding_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                ("is_chart_imported", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Metabase Unimported Chart",
                "verbose_name_plural": "Metabase Unimported Charts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["type"], name="core_metaba_type_5a55d9_idx"),
                    models.Index(
                        fields=["metabase_chart_id"],
                        name="core_metaba_metabas_a3f077_idx",
                    ),
                ],
                "unique_together": {("metabase_chart_id", "type")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNREAD", "Unread"),
                            ("READ", "Read"),
                            ("DELETE", "Delete"),
                            ("CANCEL", "Cancel"),
                        ],
                        default="UNREAD",
                        max_length=10,
                    ),
                ),
                ("status_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "search",
                    models.TextField(
                        blank=True,
                        editable=False,
                        help_text="Search field for messages",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_gids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related Global IDs",
                        related_name="notifications",
                        to="core.globalidlink",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User to notify",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "period",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("lower_bound", models.DateField()),
                ("upper_bound", models.DateField()),
                ("pay_period", models.BooleanField(default=False)),
                (
                    "interval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.interval"
                    ),
                ),
            ],
            options={
                "ordering": ("interval__ordinal", "-lower_bound"),
            },
        ),
        migrations.CreateModel(
            name="PinTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("changed", "Changed"),
                            ("authenticated", "Authenticated"),
                            ("fail", "Fail"),
                        ],
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "sealed",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Indicates if the transaction is no longer active.",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        editable=False,
                        help_text="Extra data for the transaction",
                        null=True,
                    ),
                ),
                (
                    "created_at_override",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proxy_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User that requested the pin transaction. For example the proxy user isusing his phone and the user introduce the pin to confirm.If null the owner of the pin is the requester",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proxy_pin_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        help_text="User associated with the PIN transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    (
                        "add_transaction_using_proxy_user_pin",
                        "Can add transaction using proxy user pin",
                    ),
                ),
            },
        ),
    ]
