# Generated by Django 6.0.3 on 2026-03-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dev'),
        ),
    ]
