# Generated by Django 6.0.3 on 2026-03-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicaladdress_historicalapplication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('view_email', 'Can view email field'), ('change_email', 'Can change email field'), ('view_first_name', 'Can view first_name field'), ('change_first_name', 'Can change first_name field'), ('view_last_name', 'Can view last_name field'), ('change_last_name', 'Can change last_name field'), ('view_avatar', 'Can view avatar field'), ('change_avatar', 'Can change avatar field'), ('view_signature', 'Can view signature field'), ('change_signature', 'Can change signature field'), ('view_middle_name', 'Can view middle_name field'), ('change_middle_name', 'Can change middle_name field'), ('view_display_name', 'Can view display_name field'), ('change_display_name', 'Can change display_name field'), ('view_name_suffix', 'Can view name_suffix field'), ('change_name_suffix', 'Can change name_suffix field'), ('view_nickname', 'Can view nickname field'), ('change_nickname', 'Can change nickname field'), ('view_birth_date', 'Can view birth_date field'), ('change_birth_date', 'Can change birth_date field'), ('view_gender', 'Can view gender field'), ('change_gender', 'Can change gender field'), ('view_address', 'Can view address field'), ('change_address', 'Can change address field'), ('view_phone_number', 'Can view phone_number field'), ('change_phone_number', 'Can change phone_number field'), ('view_preferred_contact', 'Can view preferred_contact field'), ('change_preferred_contact', 'Can change preferred_contact field'), ('change_reset_password_users', 'Can reset password of other users'), ('delete_users', 'Can delete users'), ('approve_profile_changes', 'Can approve profile changes'))},
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='emergency_phone_number',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='is_us_citizen',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='show_weekends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_us_citizen',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_weekends',
        ),
    ]
