# Generated by Django 6.0.3 on 2026-03-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_domain_specific_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='signed_by',
            field=models.ManyToManyField(blank=True, help_text='Pin transactions used to sign this log.', related_name='signature_logs', to='core.pintransaction'),
        ),
    ]
