# Generated by Django 6.0.3 on 2026-03-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_generalize_address_and_sign_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone (e.g. America/New_York). Falls back to SYSTEM_TIME_ZONE if blank.', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone (e.g. America/New_York). Falls back to SYSTEM_TIME_ZONE if blank.', max_length=50),
        ),
    ]
