# Generated by Django 6.0.7 on 2026-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_ticket_admin_correction_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('heating', 'Heating'), ('building_admin', 'Building Administration'), ('elevator', 'Elevators'), ('cleaning', 'Cleaning'), ('other', 'Other')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='code',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('heating', 'Heating'), ('building_admin', 'Building Administration'), ('elevator', 'Elevators'), ('cleaning', 'Cleaning'), ('other', 'Other')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('proposed', 'AI proposal'), ('approved', 'Approved'), ('assigned', 'Assigned'), ('closed', 'Closed')], db_index=True, default='new', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='number',
            field=models.CharField(help_text='Unit number, e.g. "A/1"', max_length=32),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('proposed', 'AI proposal'), ('approved', 'Approved'), ('assigned', 'Assigned'), ('closed', 'Closed')], db_index=True, default='new', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.CharField(help_text='Unit number, e.g. "A/1"', max_length=32),
        ),
    ]
